### ISSUE TITLE
perform proper validation during update job details

### ISSUE THREAD

**Issue by kasumi-1** [semperai/effectiveacceleration.ai#38]
all fields should be properly validated like on create job page

**Comment by jojedev** [comment]
This turned out to be a bigger task. I managed to add succesfully the validations, also I needed to add extra inputs because we need the user to be able to specify a maxjobTime using units, also with categories and tags (because we're using mece tags). After I added everything, I noticed that the listboxes weren't working. I spent some time debugging it and came to the conclusion that the problem comes from the headlessUI library. Basically when you use the Dialog from the headlessUI AND the listbox from headlessUI simultaneously, the html from the listbox breaks, and it doesn't allow you to hover other items or select anything.

Possible solutions:
1. Use another Dialog for this component (UpdateButton.tsx). 
2. Use another Listbox and stylize it properly.

I'll keep working on this 

![image](https://github.com/user-attachments/assets/c6041a6e-4e93-4e8b-b849-097eedc4adbe)

![image](https://github.com/user-attachments/assets/0d519de5-d14c-4aef-84e0-7d8f4190532d)

**Comment by jojedev** [comment]
At the end the neccesary solution was to use the "Select" headlessUI component. I created a new reusable component that looks the same as the rest, the dropdown isn't the same of the postJob but I think its fair enough for our Dialog editjob post.

- Added validations 
- Added Tag and components inputs 
- Made Tags comma separated
-  Max delivery time and units funcionality implemented (So the user when opens the dialog doesn't see for ex. 86400s), but instead a conversion from seconds to days.
- Fixed our dropdown issue
- Created a new "Select" component using headless UI, it is very handy to have a simple dropdown for this type of scenarios.

![image](https://github.com/user-attachments/assets/5fe77cfc-6eee-402b-b9a9-d41a5ae9382a)
![image](https://github.com/user-attachments/assets/a404b8fa-35d9-42d1-92d9-58829db6e7a1)


https://github.com/semperai/effectiveacceleration.ai/commit/9ff50bd9979481a16982d08294b1a437b5353e70
